# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    uses: ./.github/workflows/sonarcloud.yml

  deploy:
    needs: sonarcloud
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/fly.yml

  security_scans:
    needs: deploy
    uses: ./.github/workflows/security.yml