# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  maven_build:
    uses: ./.github/workflows/maven.yml

  contrast_security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build jar
        run: mvn clean install -DskipTests

      - name: Contrast SCA Action
        uses: Contrast-Security-OSS/contrast-sca-action@v1
        with:
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          filePath: pom.xml
          severity: medium
          fail: true

  snyk_scan:
    needs: contrast_security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Snyk auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk test
        run: snyk test

      - name: Snyk monitor
        run: snyk monitor

  zap_scan:
    needs: snyk_scan
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Baseline Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py \
          -t https://spring-petclinic-black-sunset-3933.fly.dev \
          -g gen.conf \
          -r zap_report.html \
          -w zap_warn.html \
          -m 5 \
          -d
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP-Report
          path: zap_report.html
      - name: Upload ZAP Warning Report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP-Warn-Report
          path: zap_warn.html

