name: Contrast Security, OWASP ZAP and Synk Scans

on:
  workflow_call:

jobs:
  contrast_security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Download Agent
        run: wget -O contrast.jar https://repo.continuumsecurity.net/contrast.jar

      - name: Build with Maven and Contrast Security
        env:
          CONTRAST__API__URL: ${{ secrets.CONTRAST_API_URL }}
          CONTRAST__API__USER: ${{ secrets.CONTRAST_API_USER }}
          CONTRAST__API__SERVICE_KEY: ${{ secrets.CONTRAST_API_SERVICE_KEY }}
          CONTRAST__API__API_KEY: ${{ secrets.CONTRAST_API_KEY }}
        run: |
          ./mvnw clean verify -DargLine="-javaagent:contrast.jar -Dcontrast.server.name=CI_SERVER -Dcontrast.env=ci -Dcontrast.override.appname=spring-petclinic"

  snyk_scan:
    needs: contrast_security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Snyk auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk test
        run: snyk test

      - name: Snyk monitor
        run: snyk monitor

  zap_scan:
    needs: synk
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Baseline Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py \
          -t https://spring-petclinic-black-sunset-3933.fly.dev \
          -g gen.conf \
          -r zap_report.html \
          -w zap_warn.html \
          -m 5 \
          -d
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP-Report
          path: zap_report.html
      - name: Upload ZAP Warning Report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP-Warn-Report
          path: zap_warn.html
